# File: docker-compose.yml

version: '3.8'

services:
  # Serviço do Servidor do Jogo
  server:
    build:
      context: .
      dockerfile: ./server/server.Dockerfile
    container_name: cardgame_server
    ports:
      - "8080:8080"
    networks:
      - cardgame-net

  # Serviço do Cliente do Jogo (para uso interativo)
  client:
    build:
      context: .
      dockerfile: ./user/client.Dockerfile
    container_name: cardgame_client
    networks:
      - cardgame-net
    depends_on:
      - server
    stdin_open: true
    tty: true
    # CORREÇÃO: Define o comando padrão a ser executado.
    # Ele inicia o programa cliente (/client_app) e passa "server" como argumento.
    command: ["/client_app", "server"]

  # Serviço para rodar os Testes Automatizados
  tests:
    build:
      context: .
      dockerfile: ./Test_files/tests.Dockerfile
    container_name: cardgame_tests
    networks:
      - cardgame-net
    depends_on:
      - server

# Define a rede customizada para os containers se comunicarem
networks:
  cardgame-net:
    driver: bridge